### ISSUE TITLE
Boolean 'false' Literal Values Not Printed

### ISSUE THREAD

**Issue by david-hosier** [flatiron/cliff#2]
Given the following script, the boolean false literal fails to get printed in my output. This happens both in 0.1 and 0.1.1.

<pre>
var cliff = require('cliff');

var objs = [];
objs.push({
    "true": true,
    "false": false,
    "name": "david"
});

cliff.putObjectRows('data', objs, ['name', 'true']);
cliff.putObjectRows('data', objs, ['name', 'false']);
</pre>

Output:

<pre>
$ node put-object-rows.js 
data:   name  true 
data:   david true 

data:   name  false 
data:   david       
</pre>

Again, I'm completely new to javascript, but I looked at the source and was unable to readily determine what the problem is.

**Comment by david-hosier** [comment]
Changing the stringifyRow() function to the below causes a false boolean literal to be printed. I don't know if this is the correct way to do this however, since I'm not really finding any information on printing boolean literals in javascript.

<pre>
  function stringifyRow(row, colorize) {
    var rowtext = '', padding, item, i, length;
    for (i = 0; i &lt; row.length; i += 1) {
      item = colorize ? row[i][colors[i]] : row[i];
      length = (row[i] || '').toString().length;
      padding = length &lt; lengths[i] ? lengths[i] - length + 2 : 2;
      if (item == false) { 
        item = new Boolean(item).toString();
      }
      rowtext += item + new Array(padding).join(' ');
    }
    
    output.push(rowtext);
  }
</pre>

**Comment by AvianFlu** [comment]
@david-hosier I'm on it, I'll see what I can do.  

@indexzero This patch seems like it could work, do you have any input?

**Comment by indexzero** [comment]
The problem with this patch is that it doesn't solve all the cases. The above code will still print the empty string for `null`

**Comment by Marak** [comment]
I think I can solve this with AvianFlu unless you want to patch it @indexzero.
